### ISSUE TITLE
앱 먹통 현상 발생

### ISSUE THREAD

**Issue by jsk41755** [Nexters/BandalArt-KMP#164]
안녕하세요.
마켓에서 다운받고 사용하다가 버그가 있는 것 같아, 문의 남겨봅니다.

반다라트 home화면의 emoji 변경 버튼을 눌렀을 때 발생하는 문제인 것 같은데요,
BandalartEmojiPicker의 이모티콘을 선택하지 않고, 빈 화면을 눌러 홈 화면으로 돌아가게 되면
앱이 먹통되는 현상이 발생됩니다.

아직 업데이트를 하고 계신 것 같아 작성해봅니다...!

**Comment by easyhooon** [comment]
오와우 제보 감사합니다 오늘 내로 해결해서 핫픽스 올려보도록 하겠습니다 ㅎㅎ

**Comment by easyhooon** [comment]
v2.1.2 버전에서 해결 되어 이슈 클로즈 하겠습니다!
