### ISSUE TITLE
바텀 시트 키보드 점프, 높이 제한 이슈

### ISSUE THREAD

**Issue by likppi10** [Nexters/BandalArt-KMP#25]
- [x] 바텀 시트의 키보드 점프함 + 키보드 생성 시, 바텀 시트의 아래쪽에 위차한 컴포넌들이 찌그러짐 
![image](https://github.com/Nexters/BandalArt-Android/assets/54509842/4338c65b-438d-4b78-af5f-66c11ad564c2)

**Comment by easyhooon** [comment]
나도 한번 만져볼께 머지하면

**Comment by likppi10** [comment]
> 바텀 시트의 키보드 점프함 + 키보드 생성 시, 바텀 시트의 아래쪽에 위차한 컴포넌들이 찌그러짐 

해결 방식 : 컨텐츠가 상태 표시줄을 넘기지 않기 위해 ModalBottomSheet의 Modifier.statusBarsPadding() 을 적용해서 ModalBottomSheet의 하단부가 아래로 밀리는 현상 발생 
기기마다의 상태 표시줄의 높이를 측정하여 ModalBottomSheet의 높이에 더해주는 방식으로 해결

해결 PR :  #30

**Comment by easyhooon** [comment]
jump 하는 현상은 계속 지켜봐야겟네 update version 이 나오면 적용해봐야겠구만 이런거 issue tracking 되고 있는거 있으려나 모르겠나

**Comment by likppi10** [comment]
구글은 개발자를 상대로 한 실험을 중지하라! 중지하라!

**Comment by easyhooon** [comment]
androidx-compose-material3 1.2.0-alpha03 -> 1.2.0-alpha04 버전으로 업그레이드 했더니, 점프하는 현상이 사라짐 -해결-

**Comment by likppi10** [comment]
+) https://android.googlesource.com/platform/frameworks/support/+/cc6a0544afd2fedf1f3e0495bd3291790be4c6c0%5E%21/#F1


![image](https://github.com/Nexters/BandalArt-Android/assets/54509842/715331f8-57b6-4cc0-83fa-ecf6d50d5645)

ModalBottomSheet가 사라질 때 부모 컴포저블의 "실제" 레이아웃의 방향을 알게 됨으로써 해결되는 무엇인가 있었나봄
