### ISSUE TITLE
이 MVP의 끝을 달성하려면..

### ISSUE THREAD

**Issue by likppi10** [Nexters/BandalArt-KMP#40]
### 당장 예측 가능한 위험
- [x] 두번째 테마 적용을 위한 수정 >> 두번째 테마가 단독으로 서브칼라를 갖기 때문에 색 적용 메커니즘이 수정되어야 할 것 같음
- [x] 처음 화면일 때의 메인 셀의 바텀 시트 >> 어찌될지 해봐야 알겠음
- [x] 삭제 후 isCompleted 상태 >> 삭제되도 isCompleted에 변화가 없음 >> 어차피 삭제 로직이 바뀌어서 다 날리면 자동으로 괜찮아질듯

### 곧 진행할 사안
- [x] 진행도 관련 메인 화면의 프로그레스바 (+ 바텀 시트의 변화도 적용되도록)
- [x] 이모지 : 메인 화면에서의 이벤트가 현재 작동하지 않음
- [x] 뷰모델로 이벤트들을 이관
~~- [ ] 컴포져블들을 세분화하여 분리~~

### 고민이 필요한 부분
- [x] 프로그레스 바가 현재 고정 테마 색상을 따라가는 것 같은데 다음 색이랑 다른 느낌이..뭔가 어색함 
- [x] 통신의 결과 로직이 좀 더 깔끔했으면 좋겠음 (지금 뭔가 뒤엉켜있다는 느낌...) + 로딩을..
- 뷰모델로 이벤트들을 이관하는 과정 (바텀시트에 있는 것들 어쩌면 좋니..)
- 컴포져블들을 세분화하여 분리하는 과정 (바텀시트에 있는 것들 어쩌면 좋니..22)

**Comment by easyhooon** [comment]
굿굿
