### ISSUE TITLE
넥나잇 때 할 것을 적어볼까요

### ISSUE THREAD

**Issue by likppi10** [Nexters/BandalArt-KMP#53]
- [x] FixedText 통일
- [x] 네이밍 수정
- [x] String 파일로 String 값 이동
- [x] 온보딩, 완료 로티 넣고 완성하기
- [x] 찢은 컴포져블 UI로 넣을지, Feature -> UI로 넣을지, designSystem에 넣을지 논의
- [x] APK 추출 
- [x] 파이어베이스 연동 (GA, crashlytics)
- [x] 앱 배포

**Comment by easyhooon** [comment]
플레이스토어에 앱 정상적으로 올라가면 close 하겠슴둥

**Comment by likppi10** [comment]
하아아아아아아잇
