### ISSUE TITLE
REQUEST failed with exception: io.ktor.client.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=, connect_timeout=unknown ms] 

### ISSUE THREAD

**Issue by easyhooon** [Nexters/BandalArt-KMP#76]
app을 사용하며, 여러번 동시에 api 를 호출할때  15초를 기다린뒤(타임아웃으로 지정한 시간)네트워크 에러 다이얼로그가 화면에 뜨고, 다시시도를 눌러도 계속 네트워크 에러 다이얼로그가 반복적으로 뜨는 이슈

바텀시트에 완료를 눌렀을때 요청하는 api일 경우 해당 이슈로 인해 완료 버튼을 눌러도 응답을 하지 않고 계속 바텀시트가 화면에 떠 있는 상태로 유지됨, 15초 후에 토스트가 출력됨

ktor 설정에 TimeOut 시간을 늘리거나, 자체 retry count를 넣어보는 방법이 떠오르긴 하나 이것이 해결 방법이 될 수 있을지는 잘 모르겠음..

**Comment by likppi10** [comment]
확실히 셀 업데이트 이후에 getlist()를 지워주고 이모티콘 업데이트를 수차례해봐도 멈추지 않는걸 보면 getList()가 너무 똥똥해서 생기는 일인것 같음.. (patch는 가져와서 처리할 게 없어서 그렇다치더라도, 가져와서 처리하는게 있다고 이런일이 발생할 수 있다는 것은 좀 문제가 있는것이니..)

**Comment by easyhooon** [comment]
ㅇㅇ Ktor 의 자체의 문제는 아닌것같고 일단 질문 답변주신것들 확인해봐야짐

**Comment by easyhooon** [comment]
REQUEST failed with exception: io.ktor.client.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=, connect_timeout=unknown ms] 로 변경됨

**Comment by easyhooon** [comment]
Network Inspection 을 확인해보면 이전까진 sending 이 정상적으로 진행이 되었으나 해당 에러가 한번 발생한 후에는 sending 자체가 안보내지는 것을 확인할 수 있었음

**Comment by easyhooon** [comment]
#117 retrofit 으로 migration 하여 해당 이슈를 임시로 해결하였으나, 왜 ktor 를 사용했을때 해당 문제가 발생했는지 아직 해결하지 못함

**Comment by easyhooon** [comment]
Ktor 버전 업데이트 되면서 이 문제도 해결됐겠지?

**Comment by likppi10** [comment]
아니..우리 서버 어디갔어
우리 서버는 미국 갔어
미국은 무슨! 정자역이겠지
