### ISSUE TITLE
디자인이 확정 되기 전에 할 수 있는 것들 

### ISSUE THREAD

**Issue by easyhooon** [Nexters/BandalArt-KMP#8]
- 프로젝트 세팅
    - [x] secrets.properties github secret 에 등록 (Server Base Url 확정된 후에)
       - https://velog.io/@2ast/Github-Github-actions%EC%97%90%EC%84%9C-Secrets%EB%A1%9C-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0
    - [x] SplashScreen API 프로젝트에 적용
    - [x] Compose Navigation 세팅 (Route, 화면 전환 기능 구현, 애니메이션 적용) -> default 애니메이션이 이미 존재)
       - 화면이 뒤집어지는 것 같은 애니메이션 등을 적용하는 것은 추후 조사해봐야 함..!
    - [x] ~Onboarding Complete 관련 DataStore 세팅 (처음에 앱에 진입했을때만 Onboarding 이 띄워지도록)~
    - [x] 프로젝트 구조 변경 like [nowinandroid](https://github.com/android/nowinandroid)
    
- API 통신
    - [x] API 호출 해보기 (샘플 코드 작성) 
    
- 라이브러리
    - [x] Compose 관련 라이브러리 Lottie-Compose, Coil-Compose 라이브러리 의존성 추가 
    - [x]  Firebase: crashlytics, analytics 연동 (반다라트 Firebase 계정 만들어진 후에) 
    
- Compose 학습
   https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-component-api-guidelines.md
    - [x] 반다라트 표 구현 해보기
            https://gist.github.com/easyhooon/1fe56cb1868e4debb148ec0ded7fa084
    - [x] BottomSheet 구현 해보기 
       - BottomSheetScaffold - dim 지원 x
       - ~ModalBottomSheetLayout - dim 지원 o~ -> Material3 ModalBottomSheet dim 지원 o
          [ModalBottomSheetLayout vs BottomSheetScaffold](https://stackoverflow.com/questions/72237961/whats-difference-between-modalbottomsheetlayout-and-bottomsheetscaffold-in-comp)
       - https://gist.github.com/likppi10/c7b34b1b0c46c99320009fc5095201e1
    - [x] Custom Dialog 구현 해보기 
    - [x] Snackbar 구현 해보기(화면 상단에 "삭제 되었습니다" 같은 메세지를 출력해야 하므로 Toast 가 아닌 Snackbar 로 구현)
       - 기본 Toast 는 출력되는 위치를 커스텀하게 옮길 수 없음!
    - [x] 상태 핸들링 학습 (State, Side Effect)
    - [x] Compose 에서의 API 통신 로직 학습

**Comment by likppi10** [comment]
- [ ] Onboarding Complete 관련 DataStore 세팅 (처음에 앱에 진입했을때만 Onboarding 이 띄워지도록)

지훈이형 이거 별도로 DataStore를 만들어야할까?
로그인 토큰의 유무로 충분히 분기가 가능하지 않을까해서!!
```
if(로그인 토큰이 있다면){
    지나가세요~
} else {
    온보딩 띄워주시고
    서버가서 로그인 토큰 받아오세요
}
```

이렇게 구현 가능하지 않을까?
오히려 별도의 DataStore를 만드는 순간 조건문만 하나 더 생기는 느낌이라..? 
장점이라면 온보딩 보여줄 boolean 변수로 직관적으로 관리한다 정도인 것 같아서 한 번 물어봤어!

**Comment by easyhooon** [comment]
생각해보니깐 로그인 토큰이 없다는 것을 어디서 체크하는지에 따라 달라질 수 있을 것 같네

**Comment by likppi10** [comment]
소셜 로그인이 포함되는 화면에서 아마 최종적으로는 토큰 체크를 하게되지 않을까

**Comment by easyhooon** [comment]
어떤 화면을 navigation 의 startDestination 으로 하는지도 생각을 해봐야할거같어 구현을 직접 해보면 더 정확하겠지만

OnBoarding 화면을 만약에 startDestination 으로 한다면 로그인 토큰이 있는지 없는지 확인을 OnBoarding화면에서 하게될텐데 토큰 확인 후에 존재하면 Home 화면으로 넘어가게 하고 (단, 이때 progress bar를 띄운다 해도 매번 아주 잠깐씩 OnBoarding 화면이 나타났다 사라지는 이슈가 발생할 수가 있을 수도..?), 없으면 온보딩 화면내에서 LaunchedEffect 블록 내에서 로그인 토큰을 요청

Home 화면(만다라트 표가 존재하는 화면)을 startDestination으로 한다면 로그인 토큰이 존재할때 그대로 화면을 유지, 로그인 토큰이 없을 경우 온보딩 화면으로 보내고 온보딩 화면에 도달 했을때 LaunchedEffect 내부에서 LoginToken을 요청하는 식으로 할 수 있겠구만 

말한대로 온보딩 체크 여부를 따로 dataStore에서 관리할 필요는 없을것같아!

**Comment by likppi10** [comment]
조옿아~
